### ISSUE TITLE
Group Projects - Milestone 2

### ISSUE THREAD

**Issue by bChakrabarty** [data301-2020-winter1/course-project-group_6002#22]
## High priority (must-fix)
- [x] Analysis is supposed to be done on a single dataset.
- [x] Add a summary section or conclusion at the end and show how well did you answer all the research question
- [x] Explore the relationship between variables, most importantly explore the data. You are supposed to analyze and visualize the dataset before jumping to research questions.

## Medium Priority (should-fix)
- [ ] Find the best genre(most shi), best platform (based on critics comment), and the emerging developer (New developer whose game shipped most) of every year 

## Low priority (fix if there is time)
- [ ] Compare user scores with the critic scores
